### ISSUE TITLE
pre-trained model and images is 404 

### ISSUE THREAD

**Issue by HadXu** [joshua-wu/deepfakes_faceswap#1]
pre-trained model and images is 404

**Comment by statham-stone** [comment]
there are other ways you can try, the anonfile is OK

**Comment by zaxs002** [comment]
get rid of github's url, just copy anonfile's url..
https://github.com/joshua-wu/deepfakes_faceswap/blob/master/anonfile.com/p7w3m0d5be/face-swap.zip
to
http://anonfile.com/p7w3m0d5be/face-swap.zip

**Comment by HadXu** [comment]
can you upload to baiduyun?I can not download  @zaxs002 thank you

**Comment by zaxs002** [comment]
No problem.
没问题老铁.上传好了给你.

**Comment by zaxs002** [comment]
BaiduYun Link: https://pan.baidu.com/s/1pLl4lz9 
Password: vddf

**Comment by HadXu** [comment]
thank you @zaxs002
