### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/cage'

### ISSUE THREAD

**Issue by raulxty** [joshua-wu/deepfakes_faceswap#10]
你好我费尽千辛万苦终于一步一步将环境装好，大概是：
安装英伟达linux驱动
安装cuda9.1
安装cuDNN7.0.5
安装python3
安装Opencv
安装tensorflow
安装tensorflow-gpu
安装Keras
然后，提示
`ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory`
根据[https://devtalk.nvidia.com/default/topic/1026198/cuda-9-0-importerror-libcublas-so-8-0/%5C](url)
又回去安装cuda8.0和cuDNN。。。
然后又提示`ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory`

`[root@gtx970 deepfakes_faceswap]# cd /usr/local/cuda-8.0/lib64
`
`[root@gtx970 lib64]# ln -s  libcudnn.so.7.*  libcudnn.so.6
`
之后`[root@gtx970 deepfakes_faceswap]# python3 train.py `却又出现
`FileNotFoundError: [Errno 2] No such file or directory: 'data/cage'
`
我尝试自己建这样的目录
`[root@gtx970 deepfakes_faceswap]# mkdir data
[root@gtx970 deepfakes_faceswap]# cd data/
[root@gtx970 data]# mkdir trump
`
却还是不行。。

**Comment by QieGao** [comment]
下边有连接，要去下载素材库

**Comment by raulxty** [comment]
但下载不了啊，404错误
