### ISSUE TITLE
Unable to download the whole project code?

### ISSUE THREAD

**Issue by zluo01** [joshua-wu/deepfakes_faceswap#9]

**Comment by creatist** [comment]
The page https://github.com/joshua-wu/deepfakes_faceswap/blob/master/anonfile.com/p7w3m0d5be/face-swap.zip  cannot be accessed.

**Comment by youerning** [comment]
链接：https://pan.baidu.com/s/1dF4f0cT 密码：mwk6
or
anonfile.com/p7w3m0d5be/face-swap.zip
anonfile.com/f6wbmfd2b2/face-swap-code.zip

**Comment by pannous** [comment]
in case your Chinese is a bit rusty: 'mwk6' is the password you have to enter.

**Comment by rockcafe3in1** [comment]
@youerning it works thanks alot

**Comment by kindect** [comment]
Why is this still open?

**Comment by zluo01** [comment]
I don't even know I post this.
